### ISSUE TITLE
Runtime Disconnected while running the cell,

### ISSUE THREAD

**Issue by FatSandwich** [demotomohiro/remocolab#93]
Why is the runtime disconnecting before it finishes installing the "remocolab.setupVNC()". Does it not work?

**Comment by demotomohiro** [comment]
It seems same issue to https://github.com/demotomohiro/remocolab/issues/88.

I ran following code in google colab's cell right now but got disconnected in a minute.

```python3
import time

begin = time.time()
for i in range(30 * 6):
  time.sleep(10)
  print(time.time() - begin)
```

I don't know why that happen.
I used google colab too long time? Are there too many people using google colab? Some trouble in the server?
That happened before and it was fixed later.

**Comment by FatSandwich** [comment]
I feel like it's something in their server and it's still happening. I hope it gets fixed!
